"use client";
import ScrollReveal from "../../../components/ScrollReveal";

export default function Page() {

  return (
    <div className="min-h-screen w-full bg-gradient-to-r from-blue-600 to-blue-500">

      {/* TOP SECTION */}
      <div className="relative px-4 sm:px-6 md:px-12 pt-16 pb-48 text-white">
        <h1 className="text-3xl sm:text-4xl md:text-5xl mt-20 font-bold leading-tight text-left">
          ODONTIS
        </h1>
        <p className="text-2xl sm:text-3xl md:text-4xl mt-2 font-bold text-left">
          Get To Know Us
        </p>

        <div className="mt-4 text-sm sm:text-base md:text-lg max-w-3xl leading-relaxed text-left">
          Please review our privacy policy and disclaimers to fully understand how Odontis handles your data.
        </div>
      </div>

      {/* ABOUT SECTION */}
      <div className="bg-white rounded-t-[60px] px-4 sm:px-6 md:px-12 py-16 -mt-32">
        <div className="max-w-4xl mx-auto">
          
          <h1 className="text-3xl sm:text-4xl md:text-5xl text-blue-600 font-bold leading-tight text-left">
            About Us
          </h1>

          <ScrollReveal>
            <p className="mt-5 text-base sm:text-lg md:text-xl leading-relaxed text-gray-700 text-justify">
              Our platform is an AI-powered dental health support system designed to assist users in understanding potential oral health concerns through image-based analysis. By using machine learning techniques, the application evaluates dental images and provides probability-based predictions that may indicate the presence of common dental conditions.
              <br /><br />
              This system is built to support awareness and early insight, not to replace professional medical judgement. The predictions generated by the platform are intended to act as a guidance tool, helping users decide when it may be appropriate to seek advice from a qualified dental professional.
              <br /><br />
              We are committed to developing technology that is accessible, transparent, and responsible. The underlying model has been trained on publicly available, anonymised datasets, ensuring ethical use of data while maintaining reliable performance. Every prediction is presented with clarity to help users better interpret results rather than rely on absolute conclusions.
              <br /><br />
              Our goal is to bridge the gap between technology and healthcare by offering a supportive, educational, and easy-to-use platform that encourages proactive dental care. By empowering users with informed insights, we aim to promote better oral health awareness and timely professional consultation.
            </p>
          </ScrollReveal>
        </div>
      </div>
    </div>
  );
}
